server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HumanResourcesDB
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ismetmustafa068@gmail.com
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

authservice:
 secret:
  secret-key: ${SECRET_KEY}
  issuer: ${ISSUER}
